services:
  - type: web
    name: spheredigital
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: REACT_APP_CLOUDINARY_CLOUD_NAME
        sync: false
      - key: REACT_APP_CLOUDINARY_UPLOAD_PRESET
        sync: false
